In [55]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [56]:
df=pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/house_price.csv")

In [57]:
df.head()

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0          37    Whitefield    3           1   3000           1      3  28000
1          43  Bommanahalli    3           1   1650          10      0  18000
2          12    Whitefield    2           0   1000           5      3  16400
3           8    Whitefield    3           0   1600           1      9  27000
4           9    Whitefield    2           1   1200           5      1  20000

In [58]:
df.count()

Unnamed: 0    1000
Location      1000
BHK           1000
Furnishing    1000
Sq.ft         1000
Old(years)    1000
Floor         1000
Price         1000
dtype: int64

In [59]:
df.Floor.unique()

array([ 3,  0,  9,  1,  8, 10,  7, 13,  2, 12, 11,  4], dtype=int64)

In [60]:
df.shape

(1000, 8)

In [61]:
df.dtypes

Unnamed: 0     int64
Location      object
BHK            int64
Furnishing     int64
Sq.ft          int64
Old(years)     int64
Floor          int64
Price          int64
dtype: object

In [62]:
df.isna().sum()

Unnamed: 0    0
Location      0
BHK           0
Furnishing    0
Sq.ft         0
Old(years)    0
Floor         0
Price         0
dtype: int64

In [63]:
df.max()

Unnamed: 0            49
Location      Whitefield
BHK                    3
Furnishing             1
Sq.ft               3155
Old(years)            10
Floor                 13
Price              45000
dtype: object

In [64]:
df.min()

Unnamed: 0               0
Location      Bommanahalli
BHK                      2
Furnishing               0
Sq.ft                  767
Old(years)               1
Floor                    0
Price                11000
dtype: object

In [65]:
#data preprarion
#df=df.iloc[:,1:]
df = df.drop(['Unnamed: 0'], axis=1)

In [66]:
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0    Whitefield    3           1   3000           1      3  28000
1  Bommanahalli    3           1   1650          10      0  18000
2    Whitefield    2           0   1000           5      3  16400
3    Whitefield    3           0   1600           1      9  27000
4    Whitefield    2           1   1200           5      1  20000

In [67]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

In [68]:
label_enc = LabelEncoder()

In [70]:
#df.iloc[:,0] = label_enc.fit_transform(df.iloc[:,0])
#Data encoding
df['Location'] = label_enc.fit_transform(df['Location'])
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         1    3           1   3000           1      3  28000
1         0    3           1   1650          10      0  18000
2         1    2           0   1000           5      3  16400
3         1    3           0   1600           1      9  27000
4         1    2           1   1200           5      1  20000

In [72]:
#data preparation
x= df.drop("Price",axis=1)
y= df["Price"]

In [73]:
x.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
0         1    3           1   3000           1      3
1         0    3           1   1650          10      0
2         1    2           0   1000           5      3
3         1    3           0   1600           1      9
4         1    2           1   1200           5      1

In [74]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.25)

In [75]:
x_train.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
597         0    2           0   1135          10      2
962         1    2           0   1290           1     10
768         0    3           0   1250           1      1
698         1    3           1   1760           5      8
755         1    3           0   1704           5     13

In [76]:
print("x_train dataset",len(x_train))
print("y_train dataset",len(y_train))

x_train dataset 750
y_train dataset 750


In [77]:
print("x_test dataset",len(x_test))
print("y_test dataset",len(y_test))

x_test dataset 250
y_test dataset 250


In [80]:
reg = LinearRegression()  #y=mx+c

In [81]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [82]:
reg.coef_

array([4233.69161144, 2552.89882654,  989.10212181,    8.33196   ,
        -24.22458419,  567.12626841])

In [83]:
reg.intercept_

214.76305760979812

In [85]:
x_test.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
805         1    2           1   1245           5      1
345         1    2           0   1088           5      1
991         1    2           0   1088           5      1
817         1    2           0   1290           1     10
417         0    2           0    960          10      3

In [86]:
y_test.head()

805    25000
345    14000
991    14000
817    26000
417    11000
Name: Price, dtype: int64

In [87]:
y_pred =reg.predict(x_test)

In [89]:
reg.predict([[1,2,0,1088,5,1]])

array([19065.42814639])

In [90]:
reg.predict([[1,3,0,2180,1,11]])

array([36484.98831059])

In [91]:
acc = (sum(y_pred)/sum(y_test))

In [ ]:
#accuracy_score(y_test,y_pred)

In [92]:
import pickle as pk